services:
  app:
    container_name: coderr_dev
    image: coderr
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: python3 manage.py runserver 0.0.0.0:8000
    stdin_open: true
    tty: true