# Generated by Django 5.2.2 on 2025-06-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="file",
            field=models.ImageField(blank=True, null=True, upload_to="offers/images/"),
        ),
    ]
